// Generated by Workspace scripts/sync-website-contract.cjs. Do not edit.
export const pages = {
  home: "Home",
  about: "About",
  locations: "Locations",
  reserve: "Reservations",
  policies: "Policies",
  menu: "Menu",
} as const;
export type PageId = keyof typeof pages;
export const routes: Record<PageId, string> = {
  home: "/",
  about: "/about",
  locations: "/locations",
  reserve: "/reserve",
  policies: "/policies",
  menu: "/menu",
};
export const sectionNames = {
  hero: "Hero",
  story: "Our story",
  locations: "Locations",
  gallery: "Gallery",
  cta: "Reservation CTA",
} as const;
export type HomeSection = keyof typeof sectionNames;
export const sectionIds = [
  "brand",
  "theme",
  "features",
  "header",
  "footer",
  "about",
  "locations",
  "reserve",
  "policies",
  "menu",
  ...Object.keys(sectionNames).map((key) => `home.${key}`),
];
export type MediaRef = {
  kind: "company-logo" | "company-cover" | "branch-cover" | "branch-photo";
  companyId: string;
  branchId?: string;
  photoId?: string;
};

type TextNode = {
  kind: "text";
  label: string;
  value: string;
  multiline?: boolean;
  nullable?: false;
  url?: boolean;
};
type NullableNode = { kind: "nullable"; label: string; value: string | null };
type NumberNode = {
  kind: "number";
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
};
type BoolNode = {
  kind: "boolean";
  label: string;
  value: boolean;
  locked?: boolean;
};
type EnumNode<T extends string = string> = {
  kind: "enum";
  label: string;
  value: T;
  options: readonly T[];
};
type MediaNode = { kind: "media"; label: string };
type ColorNode = { kind: "color"; label: string; value: string };
type BranchNode = { kind: "branch"; label: string };
interface ObjectNode<T extends Record<string, Node> = Record<string, Node>> {
  kind: "object";
  label: string;
  fields: T;
}
interface ArrayNode<T extends Node = Node> {
  kind: "array";
  label: string;
  item: T;
  length: number;
}
export type Node =
  | TextNode
  | NullableNode
  | NumberNode
  | BoolNode
  | EnumNode
  | MediaNode
  | ColorNode
  | BranchNode
  | ObjectNode
  | ArrayNode;
type Infer<N extends Node> =
  N extends ObjectNode<infer T>
    ? { [K in keyof T]: Infer<T[K]> }
    : N extends ArrayNode<infer T>
      ? Infer<T>[]
      : N extends EnumNode<infer T>
        ? T
        : N extends NumberNode
          ? number
          : N extends BoolNode
            ? boolean
            : N extends MediaNode
              ? MediaRef | null
              : N extends NullableNode | BranchNode
                ? string | null
                : string;
const text = (label: string, value = "", multiline = false): TextNode => ({
  kind: "text",
  label,
  value,
  multiline,
});
const num = (
  label: string,
  value: number,
  min: number,
  max: number,
  step = 1,
): NumberNode => ({ kind: "number", label, value, min, max, step });
const bool = (label: string, value = true, locked = false): BoolNode => ({
  kind: "boolean",
  label,
  value,
  locked,
});
const choice = <const T extends readonly string[]>(
  label: string,
  options: T,
  value: T[number] = options[0],
): EnumNode<T[number]> => ({ kind: "enum", label, options, value });
const object = <T extends Record<string, Node>>(
  label: string,
  fields: T,
): ObjectNode<T> => ({ kind: "object", label, fields });
const media = (label: string): MediaNode => ({ kind: "media", label });
const color = (label: string, value: string): ColorNode => ({
  kind: "color",
  label,
  value,
});
const copy = () => ({
  eyebrow: text("Eyebrow"),
  heading: text("Heading", "A place at the table."),
  description: text("Description", "", true),
});
const action = (label: string, destination: PageId) =>
  object(label, {
    label: text("Button label", label),
    destination: choice(
      "Destination",
      Object.keys(pages) as PageId[],
      destination,
    ),
  });
const navigation = () =>
  object(
    "Navigation",
    Object.fromEntries(
      Object.entries(pages).map(([id, label]) => [
        id,
        object(label, {
          label: text(`${label} navigation label`, label),
          visible: bool(`Show ${label}`, true, id === "reserve"),
        }),
      ]),
    ),
  ) as ObjectNode<
    Record<PageId, ObjectNode<{ label: TextNode; visible: BoolNode }>>
  >;
const locationDisplay = () => ({
  address: bool("Show address"),
  hours: bool("Show opening hours"),
  phone: bool("Show phone"),
  email: bool("Show email"),
  amenities: bool("Show amenities"),
  policies: bool("Show policies"),
  reserve: bool("Show reserve button", true, true),
  cuisine: bool("Show cuisine"),
  openStatus: bool("Show open status"),
});

export const schema = object("Website", {
  version: choice("Schema version", ["1"]),
  brand: object("Brand", {
    shortName: text("Short display name"),
    tagline: text("Tagline"),
    logo: media("Company logo"),
    logoDisplay: choice("Logo display", [
      "logo-and-name",
      "logo-only",
      "name-only",
    ]),
    logoSize: num("Logo size", 48, 24, 96),
  }),
  /**
   * What the site can do, as opposed to what it shows. A hidden navigation
   * link still leaves its page reachable; switching a capability off removes
   * the page, its routes and every button that points at it.
   */
  features: object("Features", {
    menu: bool("Menu page", true),
    reservations: bool("Online reservations", true),
    tableSelection: bool("Let guests choose their table", true),
  }),
  theme: object("Design", {
    primaryColor: color("Primary brand color", "#1d3557"),
    accentDark: color("Dark accent", "#12233b"),
    textColor: color("Text color", "#191816"),
    backgroundColor: color("Background color", "#f6f4f1"),
    typography: choice("Typography", [
      "Editorial",
      "Modern",
      "Elegant",
      "Bold",
      "Classic",
    ]),
    headingScale: num("Heading scale", 1, 0.8, 1.4, 0.05),
    spacing: choice("Spacing", ["comfortable", "compact", "generous"]),
    buttonShape: choice("Button shape", ["pill", "rounded", "square"]),
    buttonFill: choice("Button fill", ["filled", "outline"]),
    buttonSize: choice("Button size", ["normal", "compact", "large"]),
  }),
  header: object("Header", {
    variant: choice("Header appearance", ["white", "transparent", "brand"]),
    sticky: bool("Sticky header"),
    reservationLabel: text("Reservation button label", "Reserve a table"),
    navigation: navigation(),
  }),
  pages: object("Pages", {
    home: object("Home", {
      hero: object("Hero", {
        visible: bool("Show hero", true, true),
        ...copy(),
        heading: text("Heading", "Good food. Great company.", true),
        primary: action("Reserve a table", "reserve"),
        secondary: action("Explore the menu", "menu"),
        image: media("Hero image"),
        focalX: num("Image horizontal position", 50, 0, 100),
        focalY: num("Image vertical position", 50, 0, 100),
        overlay: num("Image overlay", 45, 0, 90),
        alignment: choice("Content alignment", ["left", "center", "right"]),
        variant: choice("Hero layout", ["full", "split", "centered"]),
      }),
      story: object("Our story", {
        visible: bool("Show story"),
        ...copy(),
        body: text("Story body", "", true),
        image: media("Story image"),
        variant: choice("Story layout", ["image-left", "image-right", "text"]),
      }),
      locations: object("Locations", {
        visible: bool("Show locations"),
        ...copy(),
        variant: choice("Locations layout", ["cards", "feature"]),
        imageRatio: choice("Image ratio", ["landscape", "square", "portrait"]),
        display: object("Connected card appearance", locationDisplay()),
      }),
      gallery: object("Gallery", {
        visible: bool("Show gallery"),
        ...copy(),
        variant: choice("Gallery layout", [
          "mosaic",
          "three-column",
          "large-with-two-small",
        ]),
        images: {
          kind: "array",
          label: "Gallery images",
          item: media("Image"),
          length: 6,
        } as ArrayNode<MediaNode>,
      }),
      cta: object("Reservation CTA", {
        visible: bool("Show reservation CTA", true, true),
        ...copy(),
        action: action("Reserve a table", "reserve"),
        background: choice("CTA background", ["brand", "paper", "image"]),
        image: media("CTA image"),
      }),
    }),
    about: object("About", {
      ...copy(),
      storyTitle: text("Story title", "Our story"),
      storyBody: {
        kind: "nullable",
        label: "Story body override (blank uses restaurant About)",
        value: null,
      } as NullableNode,
      image: media("About image"),
      values: {
        kind: "array",
        label: "Values",
        item: object("Value", {
          title: text("Value title"),
          description: text("Value description", "", true),
        }),
        length: 3,
      },
    }),
    locations: object("Locations page", {
      ...copy(),
      heading: text("Heading", "Find your table."),
      defaultBranchId: {
        kind: "branch",
        label: "Default branch",
      } as BranchNode,
      display: object("Connected information", locationDisplay()),
    }),
    reserve: object("Reservations", {
      heading: text("Heading", "Find your table."),
      supportingCopy: text("Supporting copy", "", true),
      background: choice("Background", ["paper", "brand", "image"]),
      image: media("Reservation background image"),
      summaryStyle: choice("Summary card", ["outlined", "filled", "minimal"]),
    }),
    policies: object("Policies", {
      heading: text("Page title", "Good to know."),
      introduction: text(
        "Introduction",
        "Everything you need before your reservation.",
        true,
      ),
      deposit: bool("Show deposit policy"),
      cancellation: bool("Show cancellation policy"),
      gracePeriod: bool("Show grace period"),
      bookingWindow: bool("Show booking window"),
    }),
    menu: object("Menu", {
      publishing: choice("Menu publishing", ["unavailable"]),
    }),
  }),
  footer: object("Footer", {
    description: text("Short description", "", true),
    showDescription: bool("Show description"),
    showLogo: bool("Show restaurant logo"),
    locationsLink: bool("Show locations link"),
    menuLink: bool("Show menu link"),
    policiesLink: bool("Show policies link"),
    instagram: { ...text("Instagram URL"), url: true },
    facebook: { ...text("Facebook URL"), url: true },
    tiktok: { ...text("TikTok URL"), url: true },
    attribution: bool("Powered by Tavlo"),
  }),
});

type ConfigShape = Infer<typeof schema>;
export type WebsiteConfigV1 = Omit<ConfigShape, "version"> & {
  version: 1;
  homeOrder: HomeSection[];
};
export function defaultsFor(node: Node): unknown {
  if (node.kind === "object")
    return Object.fromEntries(
      Object.entries(node.fields).map(([key, child]) => [
        key,
        defaultsFor(child),
      ]),
    );
  if (node.kind === "array")
    return Array.from({ length: node.length }, () => defaultsFor(node.item));
  if (node.kind === "media" || node.kind === "branch") return null;
  return node.value;
}
/**
 * Bring a stored configuration up to the current schema by filling in fields
 * added since it was written.
 *
 * This is how the schema grows. validateConfig requires every schema field to
 * be present, so adding one to `schema` would otherwise invalidate every
 * configuration already in the database — and an invalid published config is
 * dropped by the guest app, taking the restaurant's whole design with it.
 *
 * Strictly additive: it only ever supplies values that are absent. An existing
 * value is never overwritten or repaired, and unknown keys are left in place,
 * so validateConfig still rejects a malformed configuration rather than having
 * the damage papered over. Idempotent, so it is safe to run on every read.
 */
export function normalizeConfig(value: unknown): unknown {
  if (!isRecord(value)) return value;
  const fill = (node: Node, data: unknown): unknown => {
    if (node.kind === "object") {
      // Present but not an object means corrupt, not old: leave it for
      // validateConfig to report.
      if (data !== undefined && !isRecord(data)) return data;
      const source = isRecord(data) ? data : {};
      const filled: Record<string, unknown> = { ...source };
      for (const [key, child] of Object.entries(node.fields))
        filled[key] = Object.hasOwn(source, key)
          ? fill(child, source[key])
          : defaultsFor(child);
      return filled;
    }
    if (node.kind === "array") {
      // A present-but-wrong-length array is corruption, not an older schema, so
      // it is passed through for validateConfig to reject. Filling it here would
      // hide the bug that produced it.
      if (data === undefined) return defaultsFor(node);
      if (!Array.isArray(data)) return data;
      return data.map((item) => fill(node.item, item));
    }
    return data === undefined ? defaultsFor(node) : data;
  };
  // `version` and `homeOrder` sit outside the node schema, so they are carried
  // across untouched rather than walked. Key order is preserved so normalizing
  // an already-current config reproduces it byte for byte.
  const { homeOrder, version, ...rest } = value;
  const filled = fill(schema, { ...rest, version: "1" }) as Record<
    string,
    unknown
  >;
  filled.version = version;
  filled.homeOrder = homeOrder;
  const ordered: Record<string, unknown> = {};
  for (const key of Object.keys(value)) ordered[key] = filled[key];
  for (const [key, entry] of Object.entries(filled))
    if (!Object.hasOwn(ordered, key)) ordered[key] = entry;
  return ordered;
}

/**
 * One branch's images, most representative first. `coverUrl` is the branch's
 * main image; `photos` are its gallery, already in display order.
 */
export type SeedBranch = {
  id: string;
  coverUrl?: string | null;
  photos?: Array<{ id: string; url?: string | null }>;
};

/**
 * Build the pool a new draft draws its images from, ordered by how
 * representative each image is:
 *   1. the restaurant's own cover
 *   2. every branch's main image
 *   3. every branch's remaining photos, interleaved across branches so a
 *      restaurant with several locations does not seed six photos of one.
 * Ordering is deterministic, so resetting a draft reproduces the same site.
 */
export function seedAssets(
  companyId: string,
  coverUrl: string | null | undefined,
  branches: SeedBranch[] = [],
): MediaRef[] {
  const pool: MediaRef[] = [];
  if (coverUrl) pool.push({ kind: "company-cover", companyId });
  for (const branch of branches)
    if (branch.coverUrl)
      pool.push({ kind: "branch-cover", companyId, branchId: branch.id });
  const remaining = branches.map((b) =>
    (b.photos || []).filter((p) => p && p.id && p.url),
  );
  for (let round = 0; remaining.some((list) => round < list.length); round++)
    for (const [index, list] of remaining.entries())
      if (round < list.length)
        pool.push({
          kind: "branch-photo",
          companyId,
          branchId: branches[index].id,
          photoId: list[round].id,
        });
  return pool;
}

export function createDefaults(
  company: {
    id: string;
    name: string;
    logoUrl?: string | null;
    coverUrl?: string | null;
    about?: string | null;
  },
  branches: SeedBranch[] = [],
): WebsiteConfigV1 {
  const config = defaultsFor(schema) as ConfigShape;
  // A new draft must be an exact replica of the hand-coded guest site, so the
  // copy the original pages hardcode is seeded here rather than left blank.
  // Blank fields would render as empty elements and read as layout bugs.
  config.brand.shortName = company.name;
  // hero/about eyebrows are left blank on purpose: the original pages show the
  // primary branch's cuisine there, which the renderer fills in as a fallback
  // because it is connected data, not authored copy.
  config.pages.home.hero.heading = company.name;
  config.pages.home.hero.description =
    "Choose your location, your time, and the table that feels right.";
  config.pages.home.story.eyebrow = "Our story";
  config.pages.home.story.heading = `About ${company.name}.`;
  config.pages.home.story.description = company.about || "";
  config.pages.home.locations.eyebrow = "Our locations";
  config.pages.home.locations.heading = "One warm welcome.";
  // The original home card is deliberately sparse — open status, cuisine, name
  // and address. The full detail (hours, contacts, policies) belongs to the
  // Locations page, whose display toggles stay on.
  Object.assign(config.pages.home.locations.display, {
    hours: false,
    phone: false,
    email: false,
    amenities: false,
    policies: false,
  });
  config.pages.home.gallery.eyebrow = "Around the table";
  config.pages.home.gallery.heading = "Around the table";
  config.pages.home.cta.eyebrow = "Your table is waiting";
  config.pages.home.cta.heading = "Make tonight one to remember.";
  config.pages.home.cta.description =
    "Live availability, your choice of location, and a table selected by you.";
  config.pages.about.heading = `About ${company.name}.`;
  config.pages.about.storyTitle = "A place at the heart of the table.";
  config.pages.locations.heading = "Find your table.";
  config.pages.locations.description = `Choose the ${company.name} location that fits your plans.`;
  config.pages.policies.heading = "Reservation policies.";
  config.pages.policies.introduction =
    "Clear details, so the only surprise is how good dinner is.";
  if (company.logoUrl)
    config.brand.logo = { kind: "company-logo", companyId: company.id };

  // Fill every image slot from the restaurant's own library so a first draft
  // has no empty placeholders. `next` walks the pool, only repeating an image
  // once every distinct one has been used.
  const pool = seedAssets(company.id, company.coverUrl, branches);
  let cursor = 0;
  const next = (): MediaRef | null =>
    pool.length ? pool[cursor++ % pool.length] : null;
  config.pages.home.hero.image = next();
  config.pages.home.cta.image = next();
  // The closing CTA only shows its image in the "image" background mode; brand
  // colour is the fallback when there is nothing to show.
  if (config.pages.home.cta.image) config.pages.home.cta.background = "image";
  config.pages.home.story.image = next();
  config.pages.about.image = next();
  config.pages.reserve.image = next();
  config.pages.home.gallery.images = config.pages.home.gallery.images.map(
    () => next(),
  );
  return {
    ...config,
    version: 1,
    homeOrder: Object.keys(sectionNames) as HomeSection[],
  };
}
export function getAt(value: unknown, path: string): unknown {
  return path
    .split(".")
    .reduce<unknown>(
      (current, key) =>
        current != null && typeof current === "object"
          ? (current as Record<string, unknown>)[key]
          : undefined,
      value,
    );
}
export function setAt(
  config: WebsiteConfigV1,
  path: string,
  value: unknown,
): WebsiteConfigV1 {
  const next = structuredClone(config);
  const parts = path.split(".");
  const last = parts.pop()!;
  const parent = parts.reduce<unknown>(
    (current, key) => (current as Record<string, unknown>)[key],
    next,
  );
  (parent as Record<string, unknown>)[last] = value;
  return next;
}
export const isRecord = (value: unknown): value is Record<string, unknown> =>
  !!value && typeof value === "object" && !Array.isArray(value);
export function safeUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return (
      ["https:", "http:"].includes(url.protocol) &&
      !url.username &&
      !url.password
    );
  } catch {
    return false;
  }
}
export function validateConfig(value: unknown, companyId: string): string[] {
  const errors: string[] = [];
  // Locked toggles exist to guarantee a bookable site. When reservations are
  // switched off the site is not bookable by definition, so those particular
  // locks release rather than making the configuration impossible to express.
  const reservationsOn = getAt(value, "features.reservations") !== false;
  function visit(node: Node, data: unknown, path: string) {
    const fail = () =>
      errors.push(`${path}: invalid ${node.label.toLowerCase()}`);
    if (node.kind === "object") {
      if (!isRecord(data)) return fail();
      if (Object.keys(data).some((key) => !Object.hasOwn(node.fields, key)))
        fail();
      for (const [key, child] of Object.entries(node.fields))
        visit(child, data[key], `${path}.${key}`);
    } else if (node.kind === "array") {
      if (!Array.isArray(data) || data.length !== node.length) return fail();
      data.forEach((item, index) => visit(node.item, item, `${path}.${index}`));
    } else if (node.kind === "media") {
      if (data === null) return;
      if (
        !isRecord(data) ||
        data.companyId !== companyId ||
        ![
          "company-logo",
          "company-cover",
          "branch-cover",
          "branch-photo",
        ].includes(String(data.kind)) ||
        Object.keys(data).some(
          (key) => !["kind", "companyId", "branchId", "photoId"].includes(key),
        )
      )
        return fail();
      if (
        String(data.kind).startsWith("branch-") &&
        (typeof data.branchId !== "string" || !data.branchId)
      )
        fail();
      if (
        data.kind === "branch-photo" &&
        (typeof data.photoId !== "string" || !data.photoId)
      )
        fail();
      if (
        String(data.kind).startsWith("company-") &&
        (data.branchId !== undefined || data.photoId !== undefined)
      )
        fail();
      if (data.kind === "branch-cover" && data.photoId !== undefined) fail();
      if (path === "website.brand.logo" && data.kind !== "company-logo") fail();
    } else if (node.kind === "branch") {
      if (data !== null && (typeof data !== "string" || !data)) fail();
    } else if (node.kind === "nullable") {
      if (data !== null && (typeof data !== "string" || data.length > 10000))
        fail();
    } else if (node.kind === "enum") {
      if (!node.options.includes(data as string)) fail();
    } else if (node.kind === "boolean") {
      if (typeof data !== "boolean") return fail();
      if (node.locked && data !== true && reservationsOn) fail();
    } else if (node.kind === "number") {
      if (
        typeof data !== "number" ||
        !Number.isFinite(data) ||
        data < node.min ||
        data > node.max
      )
        fail();
    } else if (node.kind === "color") {
      if (typeof data !== "string" || !/^#[0-9a-f]{6}$/i.test(data)) fail();
    } else if (
      typeof data !== "string" ||
      data.length > (node.multiline ? 10000 : 300) ||
      (node.url && data !== "" && !safeUrl(data))
    )
      fail();
  }
  if (!isRecord(value) || value.version !== 1)
    return [
      "Unsupported website schema. Your stored draft has been preserved.",
    ];
  const { homeOrder, ...rest } = value;
  visit(schema, { ...rest, version: "1" }, "website");
  if (
    !Array.isArray(homeOrder) ||
    homeOrder.length !== 5 ||
    new Set(homeOrder).size !== 5 ||
    homeOrder.some(
      (key) => typeof key !== "string" || !Object.hasOwn(sectionNames, key),
    )
  )
    errors.push("Homepage sections must each appear exactly once.");
  if (
    reservationsOn &&
    getAt(value, "pages.home.cta.action.destination") !== "reserve"
  )
    errors.push("The reservation CTA must link to Reservations.");
  // A capability that is off must not leave links pointing at it: StudioSite
  // reads these visibility flags directly, so an incoherent configuration would
  // render a link to a route that redirects away. The Website Builder keeps
  // these in step automatically when a capability is toggled.
  if (!reservationsOn) {
    for (const path of [
      "header.navigation.reserve.visible",
      "pages.home.cta.visible",
    ])
      if (getAt(value, path) !== false)
        errors.push(
          "Turn off the reservation links when online reservations are off.",
        );
    if (getAt(value, "features.tableSelection") !== false)
      errors.push("Table selection requires online reservations.");
  }
  if (
    getAt(value, "features.menu") === false &&
    getAt(value, "header.navigation.menu.visible") !== false
  )
    errors.push("Turn off the menu link when the menu page is off.");
  for (const path of [
    "header.reservationLabel",
    ...Object.keys(pages).map((key) => `header.navigation.${key}.label`),
  ]) {
    if (
      typeof getAt(value, path) !== "string" ||
      !(getAt(value, path) as string).trim()
    )
      errors.push(`${path}: a label is required`);
  }
  return errors;
}
export function mediaReferences(config: WebsiteConfigV1): MediaRef[] {
  const result: MediaRef[] = [];
  function visit(value: unknown) {
    if (!value || typeof value !== "object") return;
    if (
      isRecord(value) &&
      typeof value.kind === "string" &&
      typeof value.companyId === "string"
    )
      result.push(value as MediaRef);
    else Object.values(value).forEach(visit);
  }
  visit(config);
  return result;
}
export function darken(hex: string) {
  return `#${[1, 3, 5]
    .map((i) =>
      Math.round(parseInt(hex.slice(i, i + 2), 16) * 0.72)
        .toString(16)
        .padStart(2, "0"),
    )
    .join("")}`;
}
export const typographyStacks = {
  Editorial: {
    heading: 'Georgia, "Times New Roman", serif',
    body: '"Trebuchet MS", sans-serif',
    weight: 400,
  },
  Modern: {
    heading: "Arial, sans-serif",
    body: "Arial, sans-serif",
    weight: 600,
  },
  Elegant: {
    heading: '"Palatino Linotype", Palatino, serif',
    body: '"Trebuchet MS", sans-serif',
    weight: 400,
  },
  Bold: {
    heading: "Arial, sans-serif",
    body: "Arial, sans-serif",
    weight: 900,
  },
  Classic: {
    heading: '"Times New Roman", serif',
    body: "Georgia, serif",
    weight: 700,
  },
};
export function applyPreset(
  config: WebsiteConfigV1,
  name: WebsiteConfigV1["theme"]["typography"],
): WebsiteConfigV1 {
  const settings = {
    Editorial: ["#1d3557", "#f6f4f1", "pill", "generous"],
    Modern: ["#234d46", "#ffffff", "rounded", "comfortable"],
    Elegant: ["#594635", "#faf7f0", "rounded", "generous"],
    Bold: ["#9c3024", "#fffaf1", "square", "compact"],
    Classic: ["#3e4534", "#f5f2e9", "rounded", "comfortable"],
  } as const;
  const [primaryColor, backgroundColor, buttonShape, spacing] = settings[name];
  return {
    ...config,
    theme: {
      ...config.theme,
      typography: name,
      primaryColor,
      accentDark: darken(primaryColor),
      backgroundColor,
      textColor: "#191816",
      buttonShape,
      spacing,
      buttonFill: "filled",
      buttonSize: "normal",
      headingScale: name === "Bold" ? 1.2 : 1,
    },
  };
}

/** A restaurant, as the public company endpoint returns it. */
export type TenantCompany = {
  id: string;
  name: string;
  slug: string;
  about: string | null;
  logoUrl: string | null;
  coverUrl: string | null;
  currency: string;
};

/** One row of the directory shown at the host root. */
export type TenantSummary = {
  id: string;
  name: string;
  slug: string;
  logoUrl: string | null;
  coverUrl: string | null;
  cuisineName: string | null;
};

/**
 * The published menu. The server strips hidden sections and internal ids, so
 * items are keyed by their section anchor and position.
 */
export type GuestMenu = {
  currency: string;
  updatedAt: string | null;
  sections: GuestMenuSection[];
};

export type GuestMenuSection = {
  name: string;
  eyebrow: string;
  anchor: string;
  items: GuestMenuItem[];
};

export type GuestMenuItem = {
  name: string;
  description: string;
  price: number | null;
  tags: string[];
  available: boolean;
  imageUrl: string | null;
};

export type RestaurantPolicy = {
  depositRequired: boolean;
  depositAmount: number;
  depositCurrency: string;
  bookingCutoffHours: number | null;
  freeCancelWindowHours: number | null;
  gracePeriodMinutes: number | null;
  minPartySize: number | null;
  maxPartySize: number | null;
  minReservationDurationMinutes: number | null;
  maxReservationDurationMinutes: number | null;
  cancellationWindowHours: number | null;
  lateCancelRefundPercent: number | null;
  noShowRefundPercent: number | null;
  turnTimeMinutes: number | null;
};

export type RestaurantPhoto = {
  id: string;
  url: string;
  kind: string;
  caption: string | null;
  sortOrder: number;
};

export type RestaurantHour = {
  dayOfWeek: number;
  dayLabel: string;
  isClosed: boolean;
  openTime: string | null;
  closeTime: string | null;
  summary: string;
};

export type RestaurantBranchCard = {
  id: string;
  companyId: string;
  name: string;
  companyName: string | null;
  companySlug: string | null;
  companyLogoUrl: string | null;
  currency: string;
  cuisineName: string | null;
  coverImageUrl: string | null;
  addressSummary: string;
  phone: string | null;
  timezone: string;
  isOpen: boolean;
  policySummary: {
    depositRequired: boolean;
    depositAmount: number;
    depositCurrency: string;
    bookingCutoffHours: number | null;
    freeCancelWindowHours: number | null;
    gracePeriodMinutes: number | null;
  };
};

export type RestaurantBranchDetail = RestaurantBranchCard & {
  about: string;
  email: string | null;
  hours: RestaurantHour[];
  amenities: Array<{ id: string; name: string; slug: string | null }>;
  tags: Array<{ id: string; name: string; slug: string | null }>;
  photos: RestaurantPhoto[];
  policies: RestaurantPolicy;
};

export type PreviewSnapshot = {
  revision: string;
  company: TenantCompany;
  branches: RestaurantBranchDetail[];
  menu: GuestMenu | null;
};
